import Menu from "../componentes/menu"
import "./css/base.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <Menu/>
        </header>
        <main>
          {children}
        </main>
        <footer>
          <p>©2025 Souza Arquitetura. Todos os direitos reservados.</p>
        </footer>
       </body>
    </html>
  )
}
